## Reshaping the array

In [1]:
import numpy as np

In [33]:
# reshaping the array
myarr = np.array([i for i in range(1, 21)])
print('original array : ', myarr)

reshaped = myarr.reshape(4,5)
print('reshaped array : ')
reshaped

original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
reshaped array : 


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
reshaped = myarr.reshape(2,10)
print('reshaped array : ')
reshaped

reshaped array : 


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [36]:
reshaped = myarr.reshape(10,2)
print('reshaped array : ')
reshaped

reshaped array : 


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [37]:
reshaped = myarr.reshape(20,1)
print('reshaped array : ')
reshaped

reshaped array : 


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

## Slicing

In [38]:
myarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
print('- First element : ',myarr[0])
print('- Last element : ',myarr[-1])
print('- From range 3 to 4 : ',myarr[3 : 10])

- First element :  1
- Last element :  20
- From range 3 to 4 :  [ 4  5  6  7  8  9 10]
- From range -1 to -10 :  [20]


In [49]:
demo = np.arange(1, 26)
demo = demo.reshape(5, 5)
demo

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
demo[1]

array([ 6,  7,  8,  9, 10])

In [52]:
demo[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [71]:
demo

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
# demo['outer array', 'inner array']
demo[0:3, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [106]:
from tqdm import tqdm 
import time
my_list = [i for i in range(1, 100)]
disc_count = 0  # Initialize the counter

for item in tqdm(my_list, desc="Processing List", colour='#4CC9FE'):
    # Perform some operation with each item
    # print(item)
    
    # Increase the disc count after reading each item
    disc_count += 1
    time.sleep(0.1)

print(f"\nFinal disc count: {disc_count}")


Processing List: 100%|█████████████████████████████████████████████████████████████████| 99/99 [00:10<00:00,  9.30it/s]


Final disc count: 99
