In [2]:
import pandas as np

In [5]:
arr1 = np.array([1, 2, 3, 3])
arr1

<IntegerArray>
[1, 2, 3, 3]
Length: 4, dtype: Int64

In [6]:
type(arr1)

pandas.core.arrays.integer.IntegerArray

In [9]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

<NumpyExtensionArray>
[[1, 2, 3], [4, 5, 6]]
Length: 2, dtype: object

In [10]:
type(arr2)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [16]:
# Creating a 2x3 array initialized with zeros
zeroArray = np.zeros((2, 3))
print(zeroArray)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Creating a 4x3 array initialized with zeros
oneArray = np.ones((4, 3))
print(oneArray)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# identity matrix
matrix = np.identity(4)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# loop elements using arrays
# arange([start,] stop[, step,], dtype=None, *, like=None)
loopArray = np.arange(1, 11, 3)
loopArray

array([ 1,  4,  7, 10])

In [37]:
space = np.linspace(10, 20, 10)
space

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [39]:
space1 = np.copy(space)
space1

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])