In [2]:
import numpy as np

In [61]:
# 1. shape
arr1 = np.ones((12,12))

arr2 = np.array(
    [    
        [[1, 2], [3, 4]], 
        [[2, 3], [3, 5]],
        [[2, 3], [3, 5]],
        
    ]
)

print('- Shape of matrix : ',arr1.shape)
print('- Dimention matrix : ',arr1.ndim)
print('- size of matrix : ',arr1.size) # displays number of elements present
print('- size of elements : ',arr1.itemsize) # it is double
print('- datatype : ',arr1.dtype)
print(arr1)
print()
print('-Shape of matrix : ',arr2.shape)
print('-Dimention matrix : ',arr2.ndim) 
print('-size of matrix : ',arr2.size) # displays number of elements present
print('-size of elements : ',arr2.itemsize) # it is int
print('-datatype : ',arr2.dtype)
print(arr2)

- Shape of matrix :  (12, 12)
- Dimention matrix :  2
- size of matrix :  144
- size of elements :  8
- datatype :  float64
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

-Shape of matrix :  (3, 2, 2)
-Dimention matrix :  3
-size of matrix :  12
-size of elements :  4
-datatype :  int32
[[[1 2]
  [3 4]]

 [[2 3]
  [3 5]]

 [[2 3]
  [3 5]]]


In [62]:
print(arr1.dtype)

float64


In [63]:
# Coverting the datatype
print('original array :')
print(arr1)

# modifiy array
arr1 = arr1.astype(int)

print('modified array :')
arr1

original array :
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
modified array :


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [64]:
print(arr1.dtype)

int32
