In [1]:
import numpy as np

In [2]:
x = np.arange(0,10).reshape(5, 2)

In [3]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
y = np.arange(10,20).reshape(5,2)
y

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [5]:
z = x + y
z

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

## Broadcasting term (horizontal)

In [6]:
a = np.arange(10).reshape(5,2)
b = np.arange(0, 4).reshape(2,2)
print(a, b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] [[0 1]
 [2 3]]


In [7]:
b = b[1:]

In [8]:
b

array([[2, 3]])

In [9]:
c = a + b[0:1]
print(c)

[[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]
 [10 12]]


In [10]:
a = np.arange(10)
b = np.arange(4)
print(a, b)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3]


In [11]:
c = a[:4] + b
print(c)

[0 2 4 6]


## Broadcasting term (Vertical)

In [23]:
import numpy as np

i = np.arange(0, 10).reshape(5, 2)
j = np.arange(5).reshape(5,1)

print("Array i :")
print(i)

print("\nArray j :")
print(j)


Array i :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Array j :
[[0]
 [1]
 [2]
 [3]
 [4]]


In [25]:
k = i + j
print("Array k :")
print(k)

Array k :
[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]
 [12 13]]


In [30]:
arr1 = np.arange(5).reshape(5,1)
arr2 = np.arange(5,10).reshape(1,5)

print("Array 1 :")
print(arr1)

print("Array 2 :")
print(arr2)

Array 1 :
[[0]
 [1]
 [2]
 [3]
 [4]]
Array 2 :
[[5 6 7 8 9]]


In [31]:
arr3 = arr1 + arr2
print(arr3)

[[ 5  6  7  8  9]
 [ 6  7  8  9 10]
 [ 7  8  9 10 11]
 [ 8  9 10 11 12]
 [ 9 10 11 12 13]]
